/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalha.pokemon;

/**
 *
 * @author Renan
 */
public class TelaBatalha extends javax.swing.JFrame {

    /**
     * Creates new form TelaBatalha
     */
    public TelaBatalha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        battleButton = new javax.swing.JButton();
        Pokemon2 = new javax.swing.JLabel();
        Pokemon1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display.setForeground(new java.awt.Color(0, 0, 0));
        display.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        display.setEnabled(false);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 270, 80));

        battleButton.setBackground(new java.awt.Color(255, 255, 255));
        battleButton.setForeground(new java.awt.Color(0, 0, 0));
        battleButton.setText("Batalhar");
        battleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(battleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 650, 130, 30));

        Pokemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batalha/pokemon/squirtle.png"))); // NOI18N
        Pokemon2.setText("jLabel3");
        getContentPane().add(Pokemon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 210, 220));

        Pokemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batalha/pokemon/pikachu.png"))); // NOI18N
        getContentPane().add(Pokemon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batalha/pokemon/background.jpg"))); // NOI18N
        Background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 800, 824));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void battleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battleButtonActionPerformed
        Batalha batalha = new Batalha();
        display.setText(batalha.Batalhar());
    }//GEN-LAST:event_battleButtonActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBatalha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Pokemon1;
    private javax.swing.JLabel Pokemon2;
    private javax.swing.JButton battleButton;
    private javax.swing.JTextField display;
    // End of variables declaration//GEN-END:variables
}
